"""Add page_id to comment

Revision ID: 053b5635a037
Revises: 
Create Date: 2024-09-18 12:21:35.949858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '053b5635a037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_id', sa.String(length=255), nullable=False))
        batch_op.alter_column('sentiment',
               existing_type=mysql.ENUM('Positive', 'Negative', 'Neutral'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('page_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('page_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_1', 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('post_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('sentiment',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Positive', 'Negative', 'Neutral'),
               existing_nullable=True)
        batch_op.drop_column('page_id')

    # ### end Alembic commands ###
